# Generated by Django 5.0.10 on 2026-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('log_date', models.DateField(verbose_name='Log Date')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site')),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resource Type')),
                ('resource', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resource')),
                ('session_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Session Type')),
                ('training_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Type')),
                ('report_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Report By')),
                ('schedule_slot_id', models.IntegerField(blank=True, null=True, verbose_name='Schedule Slot ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Journey Log',
                'verbose_name_plural': 'Journey Logs',
                'db_table': 'dr_journey_log',
                'ordering': ['-log_date', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyLogCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=255, verbose_name='Crew Name')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='License Number')),
                ('crew_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Crew Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Journey Log Crew',
                'verbose_name_plural': 'Journey Log Crew Members',
                'db_table': 'dr_journey_log_crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyLogDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiency_number', models.IntegerField(verbose_name='Deficiency Number')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Linked At')),
            ],
            options={
                'verbose_name': 'Journey Log DR Link',
                'verbose_name_plural': 'Journey Log DR Links',
                'db_table': 'dr_journey_log_dr',
                'managed': False,
            },
        ),
    ]
