# Generated by Django 5.0.10 on 2026-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Session Date')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Time Slot')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='End Time')),
                ('resource', models.CharField(default='AW139', max_length=50, verbose_name='Resource')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Schedule Session',
                'verbose_name_plural': 'Schedule Sessions',
                'db_table': 'dr_schedule_sessions',
                'ordering': ['session_date', 'time_slot'],
                'managed': False,
            },
        ),
    ]
