# Generated by Django 5.0.10 on 2026-07-16 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiency',
            fields=[
                ('deficiency_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Deficiency Number')),
                ('site_name', models.CharField(db_column='"SiteName"', max_length=100, verbose_name='Site Name')),
                ('resource', models.CharField(max_length=100, verbose_name='Resource')),
                ('issue_description', models.TextField(db_column='"Issue_Description"', verbose_name='Issue Description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('In Work', 'In Work'), ('Monitoring', 'Monitoring'), ('On Offer', 'On Offer'), ('On Hold', 'On Hold'), ('Cleared', 'Cleared'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('severity', models.CharField(choices=[('A', 'A - Critical'), ('B', 'B - Major'), ('C', 'C - Minor'), ('D', 'D - Cosmetic')], default='C', max_length=1, verbose_name='Severity')),
                ('sub_status_name', models.CharField(blank=True, db_column='"SubStatusName"', max_length=100, null=True, verbose_name='Sub Status')),
                ('type', models.CharField(default='Hardware', max_length=50, verbose_name='Type')),
                ('deficiency_type', models.CharField(db_column='"DeficiencyType"', default='Maintenance', max_length=50, verbose_name='Deficiency Type')),
                ('category_name', models.CharField(db_column='"CategoryName"', default='General', max_length=100, verbose_name='Category')),
                ('raised_by_name', models.CharField(db_column='"RaisedByName"', default='System', max_length=255, verbose_name='Raised By')),
                ('assignee_name', models.CharField(blank=True, db_column='"AssigneeName"', max_length=255, null=True, verbose_name='Assignee')),
                ('assignee_group_name', models.CharField(blank=True, db_column='"AssigneeGroupName"', max_length=255, null=True, verbose_name='Assignee Group')),
                ('entered_by_name', models.CharField(db_column='"EnteredByName"', default='System', max_length=255, verbose_name='Entered By')),
                ('cleared_by_name', models.CharField(blank=True, db_column='"ClearedbyName"', max_length=255, null=True, verbose_name='Cleared By')),
                ('raised_date', models.DateField(blank=True, null=True, verbose_name='Raised Date')),
                ('entered_date', models.DateField(blank=True, null=True, verbose_name='Entered Date')),
                ('cleared_date', models.DateField(blank=True, null=True, verbose_name='Cleared Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('naa_due_date', models.DateField(blank=True, db_column='"NAADueDate"', null=True, verbose_name='NAA Due Date')),
                ('on_offer_date', models.DateField(blank=True, null=True, verbose_name='On Offer Date')),
                ('_raised_date', models.DateTimeField(blank=True, db_column='"_RaisedDate"', null=True)),
                ('_entered_date', models.DateTimeField(blank=True, db_column='"_EnteredDate"', null=True)),
                ('_cleared_date', models.DateTimeField(blank=True, db_column='"_ClearedDate"', null=True)),
                ('_due_date', models.DateTimeField(blank=True, db_column='"_DueDate"', null=True)),
                ('fld_raised_date', models.DateField(blank=True, null=True)),
                ('fld_due_date', models.DateField(blank=True, null=True)),
                ('fld_last_action_taken_date', models.DateField(blank=True, null=True)),
                ('downtime', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Down Time')),
                ('interrupt_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interrupt Minutes')),
                ('device_interrupt_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Device Interrupt Minutes')),
                ('is_restricted', models.BooleanField(db_column='"Is_Restricted"', default=False, verbose_name='Is Restricted')),
                ('is_safety', models.BooleanField(db_column='"Is_Safety"', default=False, verbose_name='Is Safety')),
                ('affects_qualification', models.BooleanField(default=False, verbose_name='Affects Qualification')),
                ('dashboard_visible', models.BooleanField(default=True, verbose_name='Dashboard Visible')),
                ('spr', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_system', models.CharField(blank=True, db_column='"SubSystem"', max_length=100, null=True)),
                ('conversion', models.TextField(blank=True, null=True)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('restriction', models.TextField(blank=True, null=True)),
                ('alternate_method', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(default='Internal', max_length=255)),
                ('unique_db_identifier', models.IntegerField(blank=True, null=True)),
                ('fld_resource_id', models.IntegerField(default=1)),
                ('fld_raised_by_id', models.IntegerField(default=1)),
                ('fld_entered_by_id', models.IntegerField(default=1)),
                ('actiontaken', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deficiency',
                'verbose_name_plural': 'Deficiencies',
                'db_table': 'dr_deficiency',
                'ordering': ['-deficiency_number'],
                'managed': False,
            },
        ),
    ]
